// March 2026 payroll — hardcoded from "Scale with Video: Payroll - March 2026" PDF
// Source of truth for projected monthly payroll

export const MARCH_PAYROLL = {
  departments: {
    Internal: {
      total: 46167,
      headcount: 12,
      people: [
        { name: 'Spencer', amount: 6500 },
        { name: 'Jordan Jastro', amount: 6250 },
        { name: 'Madi', amount: 6000 },
        { name: 'Alex Brown', amount: 6000 },
        { name: 'Kole Kern', amount: 5000 },
        { name: 'Dalton Stout', amount: 5000 },
        { name: 'Zach Louis-Seize', amount: 4500 },
        { name: 'Val', amount: 2300 },
        { name: 'Miguel', amount: 1562 },
        { name: 'Bhargav Vedula', amount: 1500 },
        { name: 'Angelo', amount: 1220 },
        { name: 'Kimberly', amount: 335 },
      ],
    },
    Fulfillment: {
      total: 31884,
      headcount: 29,
      people: [
        { name: 'Danyal (Syed Ahmed)', amount: 3000 },
        { name: 'Rojot Das', amount: 3000 },
        { name: 'Waheed', amount: 2930 },
        { name: 'Aman', amount: 2465 },
        { name: 'Aqib', amount: 2405 },
        { name: 'Ahmed Khan', amount: 2345 },
        { name: 'Yves Cortez', amount: 1350 },
        { name: 'Syed Fahad', amount: 1335 },
        { name: 'Matthew Sese', amount: 1320 },
        { name: 'Irin Rai', amount: 1210 },
        { name: 'Asif Nomani', amount: 1060 },
        { name: 'Soham', amount: 1005 },
        { name: 'Maiah Dulay', amount: 1000 },
        { name: 'Muhammad Awais', amount: 910 },
        { name: 'Tina Aragon', amount: 900 },
        { name: 'Ohm (GroPro Media)', amount: 870 },
        { name: 'Addy', amount: 867 },
        { name: 'Brandon Sunny', amount: 800 },
        { name: 'Muhammad Yaseen', amount: 725 },
        { name: 'Bilal Jan', amount: 665 },
        { name: 'Rempson', amount: 600 },
        { name: 'Alberto Visuals', amount: 500 },
        { name: 'Jonathan (Stheshooter)', amount: 500 },
        { name: 'Jared', amount: 500 },
        { name: 'Cody Ray', amount: 500 },
        { name: 'Erin', amount: 395 },
        { name: 'Asad Ali', amount: 330 },
        { name: 'Gem Remulla', amount: 322 },
        { name: 'Trial Editors (3)', amount: 375 },
      ],
    },
    Sales: {
      total: 28173,
      headcount: 7,
      people: [
        { name: 'Akash', amount: 19946 },
        { name: 'Alana', amount: 3308 },
        { name: 'Zac Voynow', amount: 3249 },
        { name: 'Lily', amount: 840 },
        { name: 'Madi - Commission', amount: 480 },
        { name: 'Eric', amount: 350 },
        { name: 'Alex Brown - Commission', amount: 0 },
      ],
    },
  },
  totalPayroll: 106224,
  headcount: 48,
  marchBased: true,
  lastUpdated: 'March 2026 Payroll (baseline)',
}
